# Site settings
name: Michael Funk's Blog
title: mafunk.info
url: "http://mafunk.info"
baseurl: ""
description: >
  This is my personal blog about my adventures as a Software Developer.

#email: mafunk92@gmail.com
author: Michael Funk
avatar: "//scontent-atl3-1.xx.fbcdn.net/v/t1.0-9/10565025_10152265992031969_4427957563900783143_n.jpg?oh=b77d92917f6a0031462ae6e5d7bc8a8c&oe=57E829C0"

profile: Software Developer
twitter_username: mafunk92
github_username:  mafunk92
linkedin_username:  michaelafunk
disqus_shortname: mafunk92

permalink: /archivers/:title

gems:
 - jekyll-paginate
 - jekyll-gist
 - jekyll-sitemap
 - jekyll-seo-tag
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
